#!/usr/bin/env bash
# transfer files from our client to a server

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# assigning parametals to vairiables

path_to_file=1
ip=$2
username=3
path_to_ssh_key=4

# disabling strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# checking if the transfer was succesfful
if [ $? eq 0 ]
then
	echo "FILE WAS TRANSFERED SUCCESSFULLY"

elsei
	echo "ERROR"
