#!/usr/bin/env bash
# Configures web server by intsalling nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw allow "Nginx HTTP"

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service start nginx

# testing nginx configurations
sudo nginx -t

sudo service nginx reload
