#!/usr/bin/env bash
# Installs, configures, and starts the server
# Philip Ajuong Deng
sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World" > /var/www/html/index.nginx-debian.html'
service nginx restart
