#!/usr/bin/env bash
# write a script that displays "Best School" 10 times
# but for the 9th iteration, displays Holberton School and then Hi on a new line.

count=0
while [ $count -lt 11 ]
do
    if [ $count = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    let count+=1
done
